services:
  nuxt:
    container_name: nuxt_toollab
    env_file: .env
    build:
      context: ./docker
      target: dev
    ports:
      - "3000:3000"
    networks:
      - web
    volumes:
      - .:/app

networks:
  web:
    driver: bridge