name: Rsync Deploy Front with Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.environment == 'production' && 'main' || 'dev' }}

      - name: Deploy front with rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz --delete --exclude='.git*' --exclude='.github' --exclude='node_modules' --exclude='.env'
          path: ./
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
        env:
          REMOTE_PATH: |
            ${{ 
              github.event.inputs.environment == 'production' 
              && '/home/githubdev/production/front' 
              || '/home/githubdev/staging/front' 
            }}

      - name: Run Docker Compose on server (front)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            TARGET_DIR=${{ github.event.inputs.environment == 'production' && '/home/githubdev/production/front' || '/home/githubdev/staging/front' }}
            cd $TARGET_DIR
            docker compose -f docker-compose.yml -f docker-compose-prod.yml up -d --build